import { useEffect, useState } from 'react';
import { CheckCircle2, CreditCard, ShieldCheck, XCircle } from 'lucide-react';
import { useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import api from '../services/api';
import { formatINR } from '../utils/format';
import { Button, Card, EmptyState, Skeleton } from '../components/ui';
import { Logo } from '../components/Logo';

export default function PublicPay() {
  const { slug } = useParams();
  const [link, setLink] = useState(null), [method, setMethod] = useState('upi'), [state, setState] = useState('loading'), [message, setMessage] = useState('');
  useEffect(() => { api.get(`/public/pay/${slug}`).then(({ data }) => { setLink(data.data || data); setState('ready'); }).catch((err) => { setMessage(err.response?.data?.message || 'This payment link is unavailable.'); setState('invalid'); }); }, [slug]);
  const pay = async () => { setState('paying'); try { const { data } = await api.post(`/public/pay/${slug}`, { paymentMethod: method }); const result = data.data || data; if (result.paymentUrl || result.redirectUrl) { window.location.href = result.paymentUrl || result.redirectUrl; return; } if (result.status === 'failed' || result.success === false) { setMessage(result.message || 'Payment failed.'); setState('failed'); } else { setMessage(result.message || 'Your payment was completed successfully.'); setState('success'); } } catch (err) { setMessage(err.response?.data?.message || 'Payment could not be completed.'); setState('failed'); toast.error('Payment failed'); } };
  if (state === 'loading') return <main className="gradient-brand flex min-h-screen items-center justify-center p-4"><Skeleton className="h-[460px] w-full max-w-md" /></main>;
  if (state === 'invalid') return <main className="gradient-brand flex min-h-screen items-center justify-center p-4"><Card className="w-full max-w-md"><EmptyState icon={XCircle} title="Payment link unavailable" description={message} /></Card></main>;
  if (state === 'success') return <main className="gradient-brand flex min-h-screen items-center justify-center p-4"><Card className="w-full max-w-md text-center"><CheckCircle2 className="success-pop mx-auto h-20 w-20 text-green-500" /><h1 className="mt-5 font-display text-2xl font-bold">Payment successful</h1><p className="mt-2 text-slate-500">{message}</p><p className="mt-5 text-3xl font-bold text-navy-900">{formatINR(link.amount)}</p></Card></main>;
  if (state === 'failed') return <main className="gradient-brand flex min-h-screen items-center justify-center p-4"><Card className="w-full max-w-md text-center"><XCircle className="mx-auto h-20 w-20 text-red-500" /><h1 className="mt-5 font-display text-2xl font-bold">Payment failed</h1><p className="mt-2 text-slate-500">{message}</p><Button className="mt-6" onClick={() => setState('ready')}>Try again</Button></Card></main>;
  return <main className="gradient-brand min-h-screen px-4 py-10"><div className="mx-auto max-w-md"><div className="mb-6 flex justify-center"><Logo /></div><Card><div className="border-b border-slate-100 pb-5 text-center"><p className="text-sm text-slate-500">Paying to</p><h2 className="mt-1 font-display text-xl font-bold">{link.businessName || link.merchant?.businessName || link.merchantName}</h2><p className="mt-4 text-4xl font-bold text-navy-900">{formatINR(link.amount)}</p><p className="mt-2 text-sm text-slate-500">{link.description}</p></div><div className="py-5"><p className="mb-3 text-sm font-semibold">Choose payment method</p><div className="grid grid-cols-2 gap-3">{[['upi', 'UPI'], ['card', 'Card'], ['netbanking', 'Net banking'], ['wallet', 'Wallet']].map(([value, label]) => <button key={value} onClick={() => setMethod(value)} className={`rounded-xl border p-3 text-sm font-semibold transition ${method === value ? 'border-brand-500 bg-brand-50 text-brand-600' : 'border-slate-200 text-navy-800 hover:border-brand-200'}`}>{label}</button>)}</div></div><Button loading={state === 'paying'} onClick={pay} className="w-full"><CreditCard className="h-4 w-4" /> Pay {formatINR(link.amount)}</Button><div className="mt-4 flex items-center justify-center gap-2 text-xs text-slate-400"><ShieldCheck className="h-4 w-4" /> Encrypted and secure payment</div></Card></div></main>;
}
