import { useCallback, useEffect, useState } from 'react';
import { Copy, KeyRound, Plus, RefreshCcw, Trash2, Webhook } from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../../services/api';
import { copyText, formatDate, statusColor } from '../../utils/format';
import { Badge, Button, Card, EmptyState, Input, Modal, PageHeader } from '../../components/ui';

export default function Developers() {
  const [mode, setMode] = useState('test'), [keys, setKeys] = useState([]), [docs, setDocs] = useState(null), [logs, setLogs] = useState([]), [webhooks, setWebhooks] = useState([]);
  const [name, setName] = useState(''), [secret, setSecret] = useState(null), [hookUrl, setHookUrl] = useState(''), [loading, setLoading] = useState(false);
  const load = useCallback(async () => {
    const params = { mode };
    const results = await Promise.allSettled([api.get('/developer/api-keys', { params }), api.get('/developer/docs'), api.get('/developer/logs', { params }), api.get('/developer/webhooks', { params })]);
    const value = (i) => results[i].status === 'fulfilled' ? (results[i].value.data.data || results[i].value.data) : null;
    const k = value(0), l = value(2), w = value(3);
    setKeys(k?.apiKeys || k?.keys || (Array.isArray(k) ? k : [])); setDocs(value(1)); setLogs(l?.logs || (Array.isArray(l) ? l : [])); setWebhooks(w?.webhooks || (Array.isArray(w) ? w : []));
  }, [mode]);
  useEffect(() => { load(); }, [load]);
  const create = async (e) => { e.preventDefault(); setLoading(true); try { const { data } = await api.post('/developer/api-keys', { name, mode }); const created = data.data || data; setSecret(created.secret || created.apiSecret || created.key?.secret); setName(''); toast.success('API key created'); load(); } catch (err) { toast.error(err.response?.data?.message || 'Could not create key'); } finally { setLoading(false); } };
  const remove = async (id) => { try { await api.delete(`/developer/api-keys/${id}`); toast.success('API key deleted'); load(); } catch { toast.error('Could not delete key'); } };
  const regenerate = async (id) => { try { const { data } = await api.post(`/developer/api-keys/${id}/regenerate`); const result = data.data || data; setSecret(result.secret || result.apiSecret); toast.success('Secret regenerated'); load(); } catch { toast.error('Could not regenerate secret'); } };
  const addWebhook = async (e) => { e.preventDefault(); try { await api.post('/developer/webhooks', { url: hookUrl, mode }); toast.success('Webhook added'); setHookUrl(''); load(); } catch { toast.error('Could not add webhook'); } };
  return <div><PageHeader title="Developers" subtitle="API credentials, webhooks, documentation and request logs" actions={<div className="rounded-xl bg-slate-100 p-1">{['test', 'live'].map((v) => <button key={v} onClick={() => setMode(v)} className={`rounded-lg px-4 py-2 text-sm font-semibold capitalize ${mode === v ? 'bg-white text-brand-600 shadow-sm' : 'text-slate-500'}`}>{v}</button>)}</div>} />
    <div className="grid gap-6 xl:grid-cols-2"><Card><h2 className="font-display font-bold">API keys</h2><form onSubmit={create} className="mt-4 flex gap-2"><Input required aria-label="Key name" placeholder="Key name" value={name} onChange={(e) => setName(e.target.value)} /><Button loading={loading} type="submit"><Plus className="h-4 w-4" /> Create</Button></form><div className="mt-5 space-y-3">{keys.length ? keys.map((key) => <div key={key.id} className="rounded-xl border border-slate-100 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{key.name}</p><code className="text-xs text-slate-500">{key.prefix || key.publicKey || key.key || '••••••••'}</code></div><Badge className={statusColor(key.status || 'active')}>{key.status || 'active'}</Badge></div><div className="mt-3 flex gap-2"><Button variant="secondary" className="!px-3 !py-2 text-xs" onClick={() => regenerate(key.id)}><RefreshCcw className="h-3.5 w-3.5" /> Regenerate</Button><Button variant="danger" className="!px-3 !py-2 text-xs" onClick={() => remove(key.id)}><Trash2 className="h-3.5 w-3.5" /> Delete</Button></div></div>) : <EmptyState icon={KeyRound} title={`No ${mode} keys`} />}</div></Card>
    <Card><h2 className="font-display font-bold">Webhooks</h2><form onSubmit={addWebhook} className="mt-4 flex gap-2"><Input required type="url" aria-label="Webhook URL" placeholder="https://example.com/webhook" value={hookUrl} onChange={(e) => setHookUrl(e.target.value)} /><Button type="submit"><Plus className="h-4 w-4" /></Button></form><div className="mt-5 space-y-3">{webhooks.length ? webhooks.map((hook) => <div key={hook.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{hook.url}</p><p className="text-xs text-slate-500">{hook.events?.join(', ') || 'All payment events'}</p></div><Badge className={statusColor(hook.status || 'active')}>{hook.status || 'active'}</Badge></div>) : <EmptyState icon={Webhook} title="No webhooks" />}</div></Card>
    <Card><h2 className="font-display font-bold">Quick documentation</h2><div className="mt-4 rounded-xl bg-navy-900 p-4 text-sm text-slate-200"><code className="whitespace-pre-wrap">{docs?.quickStart || docs?.content || docs?.baseUrl || 'Use your API key as a Bearer token when calling the India Pay Now API.'}</code></div>{docs?.url && <a href={docs.url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-brand-600">Open full documentation →</a>}</Card>
    <Card className="overflow-x-auto"><h2 className="font-display font-bold">Recent API logs</h2><table className="mt-4 w-full min-w-[520px] text-left text-xs"><thead><tr className="text-slate-500"><th className="p-2">Time</th><th className="p-2">Method</th><th className="p-2">Endpoint</th><th className="p-2">Status</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id} className="border-t border-slate-50"><td className="p-2">{formatDate(log.createdAt || log.created_at)}</td><td className="p-2 font-semibold">{log.method}</td><td className="p-2">{log.endpoint || log.path}</td><td className="p-2">{log.statusCode || log.status}</td></tr>)}</tbody></table></Card></div>
    <Modal open={!!secret} onClose={() => setSecret(null)} title="Save your API secret"><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">This secret is shown only once. Store it securely.</div><div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-100 p-3"><code className="min-w-0 flex-1 break-all text-sm">{secret}</code><Button variant="secondary" className="!p-2" onClick={() => copyText(secret).then(() => toast.success('Secret copied'))}><Copy className="h-4 w-4" /></Button></div></Modal>
  </div>;
}
