import { useCallback, useEffect, useState } from 'react';
import { Copy, ExternalLink, Link2, Mail, MessageCircle, Share2, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../../services/api';
import { copyText, formatDate, formatINR, statusColor } from '../../utils/format';
import { Badge, Button, Card, EmptyState, Input, PageHeader, Textarea } from '../../components/ui';

export default function PaymentLinks() {
  const empty = { customerName: '', customerEmail: '', customerMobile: '', amount: '', description: '', expiry: '' };
  const [form, setForm] = useState(empty), [items, setItems] = useState([]), [loading, setLoading] = useState(false);
  const load = useCallback(() => api.get('/payment-links').then(({ data }) => setItems(data.data?.paymentLinks || data.paymentLinks || data.data || [])).catch(() => toast.error('Could not load links')), []);
  useEffect(() => { load(); }, [load]);
  const submit = async (e) => { e.preventDefault(); setLoading(true); try { await api.post('/payment-links', { ...form, amount: Number(form.amount) }); toast.success('Payment link created'); setForm(empty); load(); } catch (err) { toast.error(err.response?.data?.message || 'Could not create link'); } finally { setLoading(false); } };
  const disable = async (id) => { try { await api.delete(`/payment-links/${id}`); toast.success('Link disabled'); load(); } catch { toast.error('Could not disable link'); } };
  const urlFor = (link) => link.url || link.paymentUrl || `${window.location.origin}/pay/${link.slug}`;
  return <div><PageHeader title="Payment links" subtitle="Create shareable checkout links" />
    <div className="grid gap-6 lg:grid-cols-[380px_1fr]"><Card><h2 className="mb-4 font-display font-bold">Create a link</h2><form onSubmit={submit} className="space-y-3"><Input required label="Customer name" value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value })} /><Input required type="email" label="Email" value={form.customerEmail} onChange={(e) => setForm({ ...form, customerEmail: e.target.value })} /><Input required label="Mobile" value={form.customerMobile} onChange={(e) => setForm({ ...form, customerMobile: e.target.value })} /><Input required min="1" type="number" label="Amount (₹)" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /><Textarea label="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><Input type="datetime-local" label="Expiry" value={form.expiry} onChange={(e) => setForm({ ...form, expiry: e.target.value })} /><Button loading={loading} type="submit" className="w-full"><Link2 className="h-4 w-4" /> Create link</Button></form></Card>
    <div className="space-y-4">{items.length ? items.map((link) => { const url = urlFor(link); const message = encodeURIComponent(`Pay ${formatINR(link.amount)} securely: ${url}`); return <Card key={link.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{link.customerName || link.customer?.name || 'Payment link'}</h3><Badge className={statusColor(link.status || 'active')}>{link.status || 'active'}</Badge></div><p className="mt-1 text-xl font-bold text-navy-900">{formatINR(link.amount)}</p><p className="text-xs text-slate-500">{link.expiry || link.expiresAt ? `Expires ${formatDate(link.expiry || link.expiresAt)}` : 'No expiry'}</p></div><a href={url} target="_blank" rel="noreferrer" className="text-brand-600"><ExternalLink className="h-5 w-5" /></a></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" className="!px-3 !py-2 text-xs" onClick={() => copyText(url).then(() => toast.success('Copied'))}><Copy className="h-4 w-4" /> Copy</Button>{navigator.share && <Button variant="secondary" className="!px-3 !py-2 text-xs" onClick={() => navigator.share({ title: 'Payment link', url })}><Share2 className="h-4 w-4" /> Share</Button>}<a href={`https://wa.me/?text=${message}`} target="_blank" rel="noreferrer"><Button variant="secondary" className="!px-3 !py-2 text-xs"><MessageCircle className="h-4 w-4" /> WhatsApp</Button></a><a href={`mailto:${link.customerEmail || ''}?subject=Payment request&body=${message}`}><Button variant="secondary" className="!px-3 !py-2 text-xs"><Mail className="h-4 w-4" /> Email</Button></a><Button variant="danger" className="!px-3 !py-2 text-xs" onClick={() => disable(link.id)}><Trash2 className="h-4 w-4" /> Disable</Button></div></Card>; }) : <Card><EmptyState icon={Link2} title="No payment links" description="Create your first secure payment link." /></Card>}</div></div></div>;
}
