import { useCallback, useEffect, useState } from 'react';
import { Download, Landmark, Send } from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../../services/api';
import { formatDate, formatINR, statusColor } from '../../utils/format';
import { Badge, Button, Card, EmptyState, Input, Modal, PageHeader, StatCard } from '../../components/ui';

export default function Settlements() {
  const [data, setData] = useState({}), [open, setOpen] = useState(false), [amount, setAmount] = useState(''), [loading, setLoading] = useState(false);
  const load = useCallback(() => api.get('/settlements').then(({ data: res }) => setData(res.data || res)).catch(() => toast.error('Could not load settlements')), []);
  useEffect(() => { load(); }, [load]);
  const history = data.settlements || data.history || (Array.isArray(data) ? data : []);
  const request = async (e) => { e.preventDefault(); setLoading(true); try { await api.post('/settlements/request', { amount: Number(amount) }); toast.success('Settlement requested'); setOpen(false); setAmount(''); load(); } catch (err) { toast.error(err.response?.data?.message || 'Request failed'); } finally { setLoading(false); } };
  const download = () => { const csv = [['ID', 'Date', 'Amount', 'Status', 'Reference'], ...history.map((s) => [s.id, s.createdAt || s.created_at, s.amount, s.status, s.reference || s.utr || ''])].map((r) => r.map((v) => `"${String(v ?? '').replaceAll('"', '""')}"`).join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'settlements.csv'; a.click(); URL.revokeObjectURL(a.href); };
  return <div><PageHeader title="Settlements" subtitle="Move collected funds to your bank" actions={<div className="flex gap-2"><Button variant="secondary" onClick={download}><Download className="h-4 w-4" /> Report</Button><Button onClick={() => setOpen(true)}><Send className="h-4 w-4" /> Request settlement</Button></div>} /><div className="grid gap-4 md:grid-cols-3"><StatCard label="Available" value={formatINR(data.available ?? data.availableSettlement)} icon={Landmark} tone="blue" /><StatCard label="Processing" value={formatINR(data.processing ?? data.processingAmount)} icon={Landmark} tone="amber" /><StatCard label="Settled" value={formatINR(data.settled ?? data.settledAmount)} icon={Landmark} tone="green" /></div><Card className="mt-6 overflow-x-auto"><h2 className="mb-4 font-display font-bold">Settlement history</h2>{history.length ? <table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="text-slate-500">{['ID', 'Requested', 'Amount', 'Bank / UTR', 'Status'].map((h) => <th key={h} className="border-b border-slate-100 p-3 font-medium">{h}</th>)}</tr></thead><tbody>{history.map((s) => <tr key={s.id} className="border-b border-slate-50"><td className="p-3 font-medium">{s.settlementId || s.id}</td><td className="p-3">{formatDate(s.createdAt || s.created_at || s.date)}</td><td className="p-3 font-semibold">{formatINR(s.amount)}</td><td className="p-3">{s.utr || s.reference || s.bankAccount || '—'}</td><td className="p-3"><Badge className={statusColor(s.status)}>{s.status}</Badge></td></tr>)}</tbody></table> : <EmptyState icon={Landmark} title="No settlements yet" />}</Card><Modal open={open} onClose={() => setOpen(false)} title="Request settlement"><form onSubmit={request} className="space-y-4"><Input required type="number" min="1" max={data.available ?? data.availableSettlement} label="Amount" value={amount} onChange={(e) => setAmount(e.target.value)} /><p className="text-sm text-slate-500">Available: {formatINR(data.available ?? data.availableSettlement)}</p><Button loading={loading} type="submit">Submit request</Button></form></Modal></div>;
}
