import { useCallback, useEffect, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../../services/api';
import { formatDate, statusColor } from '../../utils/format';
import { Badge, Button, Card, EmptyState, Modal, PageHeader, Select, Skeleton, Textarea } from '../../components/ui';

export default function KYC() {
  const [items, setItems] = useState([]), [loading, setLoading] = useState(true), [selected, setSelected] = useState(null), [status, setStatus] = useState('approved'), [reason, setReason] = useState(''), [saving, setSaving] = useState(false);
  const load = useCallback(() => { setLoading(true); api.get('/admin/kyc').then(({ data }) => setItems(data.data?.kyc || data.kyc || data.data || [])).catch(() => toast.error('Could not load KYC requests')).finally(() => setLoading(false)); }, []);
  useEffect(() => { load(); }, [load]);
  const update = async (e) => { e.preventDefault(); setSaving(true); try { await api.put(`/admin/kyc/${selected.id}`, { status, ...(reason && { reason }) }); toast.success('KYC status updated'); setSelected(null); load(); } catch (err) { toast.error(err.response?.data?.message || 'Update failed'); } finally { setSaving(false); } };
  return <div><PageHeader title="KYC" subtitle="Review and verify merchant identities" /><Card className="overflow-x-auto">{loading ? <Skeleton className="h-72" /> : items.length ? <table className="w-full min-w-[820px] text-left text-sm"><thead><tr className="text-slate-500">{['Merchant', 'PAN', 'GSTIN', 'Submitted', 'Status', 'Action'].map((h) => <th key={h} className="border-b border-slate-100 p-3 font-medium">{h}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-slate-50"><td className="p-3"><p className="font-semibold">{item.businessName || item.merchant?.businessName || item.name}</p><p className="text-xs text-slate-500">{item.email || item.merchant?.email}</p></td><td className="p-3">{item.pan || item.panNumber || '—'}</td><td className="p-3">{item.gstin || item.gstNumber || '—'}</td><td className="p-3">{formatDate(item.createdAt || item.created_at || item.submittedAt)}</td><td className="p-3"><Badge className={statusColor(item.status)}>{item.status}</Badge></td><td className="p-3"><Button variant="soft" className="!px-3 !py-2 text-xs" onClick={() => { setSelected(item); setStatus(item.status === 'pending' ? 'approved' : item.status); }}>Review</Button></td></tr>)}</tbody></table> : <EmptyState icon={ShieldCheck} title="No KYC requests" />}</Card><Modal open={!!selected} onClose={() => setSelected(null)} title="Review KYC"><form onSubmit={update} className="space-y-4"><Select label="Decision" value={status} onChange={(e) => setStatus(e.target.value)}><option value="approved">Approve</option><option value="rejected">Reject</option><option value="pending">Keep pending</option></Select><Textarea label="Review note" value={reason} onChange={(e) => setReason(e.target.value)} /><Button loading={saving} type="submit">Update KYC</Button></form></Modal></div>;
}
